pm.test("Response status code is 200", function () {
    pm.expect(pm.response.code).to.equal(200);
});


pm.test("Content-Type header is text/html", function () {
    pm.expect(pm.response.headers.get("Content-Type")).to.include("text/html");
});


pm.test("Response time is less than 200ms", function () {
  pm.expect(pm.response.responseTime).to.be.below(200);
});


pm.test("Response body matches the expected schema", function () {
    // No specific schema validation library available in Postman, so just checking if the response is a valid JSON
    pm.expect(pm.response.json()).to.not.be.an('undefined');
});


pm.test("Response body is not empty", function () {
    pm.expect(pm.response.text()).to.not.be.empty;
});
